name: Gold Price Scraper

on:
  schedule:
    # Runs daily at 11:00 AM IST (5:30 AM UTC)
    - cron: '30 5 * * *'
  workflow_dispatch: # Allows manual triggering
  
env:
  PYTHON_VERSION: '3.9'

jobs:
  scrape-gold-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Prevent long-running jobs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
        echo "Chrome version: $CHROME_VERSION"
        
        # Use Chrome for Testing API for newer Chrome versions (115+)
        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d "." -f1)
        
        if [ "$CHROME_MAJOR_VERSION" -ge 115 ]; then
          echo "Using Chrome for Testing API for Chrome $CHROME_VERSION"
          # Try direct download from Chrome for Testing
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip" || {
            echo "Direct download failed, trying latest stable"
            wget -O /tmp/chromedriver.zip "https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json" | head -1
            # Fallback to a known working version
            wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chromedriver-linux64.zip"
          }
        else
          echo "Using legacy ChromeDriver API for Chrome $CHROME_VERSION"
          # Fallback for older Chrome versions
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}")
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        fi
        
        # Extract and install
        cd /tmp
        unzip -q chromedriver.zip
        
        # Handle different archive structures
        if [ -f "chromedriver-linux64/chromedriver" ]; then
          sudo cp chromedriver-linux64/chromedriver /usr/local/bin/
        elif [ -f "chromedriver" ]; then
          sudo cp chromedriver /usr/local/bin/
        else
          echo "ChromeDriver binary not found in expected locations"
          ls -la
          exit 1
        fi
        
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Firebase service account file
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase_service_account.json
        
    - name: Run Tanishq scraper for Bangalore
      run: |
        python3 main_scraper.py \
          --jewellers tanishq \
          --cities Bangalore \
          --days 30 \
          --firebase-key firebase_service_account.json \
          --collection gold_prices
      continue-on-error: true
      id: bangalore-scrape
      
    - name: Run Tanishq scraper for Madhubani
      run: |
        python3 main_scraper.py \
          --jewellers tanishq \
          --cities Madhubani \
          --days 30 \
          --firebase-key firebase_service_account.json \
          --collection gold_prices
      continue-on-error: true
      id: madhubani-scrape
      
    - name: Clean up credentials
      if: always()
      run: |
        rm -f firebase_service_account.json
        
    - name: Report results
      if: always()
      run: |
        echo "Scraping Summary:"
        echo "Bangalore: ${{ steps.bangalore-scrape.outcome }}"
        echo "Madhubani: ${{ steps.madhubani-scrape.outcome }}"
        
        if [[ "${{ steps.bangalore-scrape.outcome }}" == "failure" && "${{ steps.madhubani-scrape.outcome }}" == "failure" ]]; then
          echo "❌ Both scraping jobs failed"
          exit 1
        elif [[ "${{ steps.bangalore-scrape.outcome }}" == "failure" || "${{ steps.madhubani-scrape.outcome }}" == "failure" ]]; then
          echo "⚠️ One scraping job failed"
        else
          echo "✅ All scraping jobs completed successfully"
        fi 